# Generated by Django 3.2.9 on 2021-12-08 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0001_initial'),
        ('institutos', '0001_initial'),
        ('carreras', '0001_initial'),
        ('inscripciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutoscarreras',
            name='relacion_instituto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutosInscripcion', to='institutos.institutos'),
        ),
        migrations.AddField(
            model_name='estudiantessegundacarrera',
            name='relacion_estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantesPreinscripcionDos', to='estudiantes.estudiantes'),
        ),
        migrations.AddField(
            model_name='estudiantessegundacarrera',
            name='relacion_inscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripcionPreinscripcionDos', to='inscripciones.inscripciones'),
        ),
        migrations.AddField(
            model_name='estudiantessegundacarrera',
            name='segunda_carrera',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrerasPreinscripcionDos', to='carreras.carreras'),
        ),
        migrations.AddField(
            model_name='estudiantesprimercarrera',
            name='primer_carrera',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrerasPreinscripcionUno', to='carreras.carreras'),
        ),
        migrations.AddField(
            model_name='estudiantesprimercarrera',
            name='relacion_estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantesPreinscripcionUno', to='estudiantes.estudiantes'),
        ),
        migrations.AddField(
            model_name='estudiantesprimercarrera',
            name='relacion_inscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripcionPreinscripcionUno', to='inscripciones.inscripciones'),
        ),
        migrations.AddField(
            model_name='estudiantesinscripcionescompletas',
            name='relacion_primer_carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relacionCarreraUno', to='inscripciones.estudiantesprimercarrera'),
        ),
        migrations.AddField(
            model_name='estudiantesinscripcionescompletas',
            name='relacion_segunda_carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relacionCarreraDos', to='inscripciones.estudiantessegundacarrera'),
        ),
    ]
