# Generated by Django 3.2.9 on 2021-12-08 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jerarquicos',
            name='relacion_jerarquico_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jerarquicoUsuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jerarquicos',
            name='relacion_rol_jerarquico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargosJerarquicos', to='institutos.rolesjerarquicos'),
        ),
        migrations.AddField(
            model_name='institutosjerarquicos',
            name='relacion_instituto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutoResponsable', to='institutos.institutos'),
        ),
        migrations.AddField(
            model_name='institutosjerarquicos',
            name='relacion_jerarquico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsableInstituto', to='institutos.jerarquicos'),
        ),
    ]
