# Generated by Django 3.2.9 on 2021-12-07 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carreras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_carrera', models.CharField(max_length=100, verbose_name='Carrera')),
                ('resolucion_carrera', models.CharField(max_length=10, verbose_name='Resolución')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
            },
        ),
        migrations.CreateModel(
            name='TurnosCarreras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno_carrera', models.CharField(max_length=1, verbose_name='Turno implicíto')),
                ('turno_carrera_completo', models.CharField(max_length=6, verbose_name='Turno explicíto')),
            ],
            options={
                'verbose_name': 'Turno de Carrera',
                'verbose_name_plural': 'Turnos de Carrera',
            },
        ),
        migrations.CreateModel(
            name='LimitacionesCarreras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_aceptada', models.PositiveIntegerField(default=0, verbose_name='Totales de inscripciones aceptadas')),
                ('cantidad_lista_espera', models.PositiveIntegerField(default=0, verbose_name='Totales de inscripciones aceptadas en lista de espera')),
                ('fecha_inicio', models.DateField(blank=True, verbose_name='Fecha de inicio de preinscripción')),
                ('fecha_fin', models.DateField(blank=True, verbose_name='Fecha de cierre de preinscripción')),
                ('relacion_carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limitesCarreras', to='carreras.carreras')),
            ],
            options={
                'verbose_name': 'Limitación',
                'verbose_name_plural': 'Limitaciones',
            },
        ),
        migrations.AddField(
            model_name='carreras',
            name='relacion_turno_carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnosCarreras', to='carreras.turnoscarreras'),
        ),
    ]
